CREATE TABLE Person(
    id int GENERATED by DEFAULT as IDENTITY PRIMARY KEY ,
    name varchar(100) NOT NULL ,
    age int,
    email varchar(100)
);

INSERT INTO Person (name, age, email) VALUES ('Tom', 25, 'tom@mail.ru');
INSERT INTO Person (name, age, email) VALUES ('Bob', 51, 'bob@mail.ru');
INSERT INTO Person (name, age, email) VALUES ('Nik', 35, 'nik@mail.ru');